markdown: kramdown
highlighter: pygments
baseurl: /behaviac
permalink: /:categories/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-11132649-2

repository: https://github.com/TencentOpen/behaviac
help_url: https://github.com/TencentOpen/behaviac
collections:
  docs:
    output: true

name: behaviac • 游戏AI开发框架组件
description: 游戏AI开发框架组件, support Unity 3D, Cocos 2d, SDL and other game engines.
url: http://tencentopen.github.io/behaviac

gems:
  - jekyll-feed
