markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments
baseurl: /behaviac
permalink: /:categories/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-11132649-2

repository: https://github.com/TencentOpen/behaviac
help_url: https://github.com/TencentOpen/behaviac
collections:
  docs:
    output: true

name: behaviac Game AI, Behavior Tree, Finite State Machine, Hierarchical Task Network, BT FSM HTN
description: Advanced Game AI framework, Prototype Design, Client and Server, Unity 3D, Cocos2d-x, SDL and other game engine.
url: http://tencentopen.github.io/behaviac

gems:
  - jekyll-feed
